[package]
name = "smart-contract-learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.4.0"
near-sdk = "3.0.0"
serde = "1.0.14"
